# Generated by Django 4.2.30 on 2026-04-10 17:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDaTrilha', models.CharField(max_length=100, verbose_name='Nome da trilha')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('semestre', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Semestre')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDoTopico', models.CharField(max_length=100, verbose_name='Nome do tópico')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='estudos.trilha')),
            ],
        ),
        migrations.CreateModel(
            name='Subtopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDoSubtopico', models.CharField(max_length=100, verbose_name='Nome do subtópico')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopicos', to='estudos.topico')),
            ],
        ),
    ]
