# Generated by Django 4.2.30 on 2026-04-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudos', '0002_remove_trilha_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subtopico',
        ),
    ]
